name: on_pull_request
on:
  pull_request:
    branches: [main]
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Tools
        run: |
          mkdir -p $HOME/bin
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/bin
          echo $HOME/bin >> $GITHUB_PATH
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo $HOME/.poetry/bin >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install Python Requirements
        env:
          POETRY_VIRTUALENVS_CREATE: "false"
        run: |
          poetry install
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run pylint -j 0 ywit_event_countdown | reviewdog -reporter=github-pr-check -diff="git diff master" -efm="%f:%l:%c: %m"